#!/bin/bash

# while true == run always.
while true; do
	# if the process doesn't run start it. 
	# pid of process is greater then nothing or run program.
	pgrep $@ > /dev/null || ($@ &)
	# sleep some to not strain the system 
	sleep 2
done
